// AUTOGENERATED by `pnpm tts`. Edit AddingCommands.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "AddingCommands",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "AddingCommands/title.wav",
      durationInSeconds: 15.55,
      durationInFrames: 467,
    },
    {
      id: "context",
      audioFile: "AddingCommands/context.wav",
      durationInSeconds: 19.2,
      durationInFrames: 576,
    },
    {
      id: "factories",
      audioFile: "AddingCommands/factories.wav",
      durationInSeconds: 26.075,
      durationInFrames: 783,
    },
    {
      id: "why-factories",
      audioFile: "AddingCommands/why-factories.wav",
      durationInSeconds: 22.799999999999997,
      durationInFrames: 684,
    },
    {
      id: "bindings",
      audioFile: "AddingCommands/bindings.wav",
      durationInSeconds: 25.925,
      durationInFrames: 778,
    },
    {
      id: "lifecycle",
      audioFile: "AddingCommands/lifecycle.wav",
      durationInSeconds: 24.4,
      durationInFrames: 732,
    },
    {
      id: "outro",
      audioFile: "AddingCommands/outro.wav",
      durationInSeconds: 20.049999999999997,
      durationInFrames: 602,
    },
  ],
  totalDurationInFrames: 4622,
};
