// AUTOGENERATED by `pnpm tts`. Edit CommandFramework.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "CommandFramework",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "CommandFramework/title.wav",
      durationInSeconds: 14.35,
      durationInFrames: 431,
    },
    {
      id: "three-pieces",
      audioFile: "CommandFramework/three-pieces.wav",
      durationInSeconds: 16.799999999999997,
      durationInFrames: 504,
    },
    {
      id: "subject",
      audioFile: "CommandFramework/subject.wav",
      durationInSeconds: 15.725,
      durationInFrames: 472,
    },
    {
      id: "code",
      audioFile: "CommandFramework/code.wav",
      durationInSeconds: 27.375,
      durationInFrames: 822,
    },
    {
      id: "outro",
      audioFile: "CommandFramework/outro.wav",
      durationInSeconds: 14.85,
      durationInFrames: 446,
    },
  ],
  totalDurationInFrames: 2675,
};
