// AUTOGENERATED by `pnpm tts`. Edit Hardware.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "Hardware",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "Hardware/title.wav",
      durationInSeconds: 16.099999999999998,
      durationInFrames: 483,
    },
    {
      id: "kraken",
      audioFile: "Hardware/kraken.wav",
      durationInSeconds: 20.175,
      durationInFrames: 606,
    },
    {
      id: "cancoder",
      audioFile: "Hardware/cancoder.wav",
      durationInSeconds: 19.974999999999998,
      durationInFrames: 600,
    },
    {
      id: "canivore",
      audioFile: "Hardware/canivore.wav",
      durationInSeconds: 20.65,
      durationInFrames: 620,
    },
    {
      id: "outro",
      audioFile: "Hardware/outro.wav",
      durationInSeconds: 13.875,
      durationInFrames: 417,
    },
  ],
  totalDurationInFrames: 2726,
};
