// AUTOGENERATED by `pnpm tts`. Edit Introduction.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "Introduction",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "Introduction/title.wav",
      durationInSeconds: 12.65,
      durationInFrames: 380,
    },
    {
      id: "audience",
      audioFile: "Introduction/audience.wav",
      durationInSeconds: 15.4,
      durationInFrames: 462,
    },
    {
      id: "what-youll-learn",
      audioFile: "Introduction/what-youll-learn.wav",
      durationInSeconds: 15.950000000000001,
      durationInFrames: 479,
    },
    {
      id: "cta",
      audioFile: "Introduction/cta.wav",
      durationInSeconds: 14.1,
      durationInFrames: 423,
    },
  ],
  totalDurationInFrames: 1744,
};
