// AUTOGENERATED by `pnpm tts`. Edit LoggingImplementation.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "LoggingImplementation",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "LoggingImplementation/title.wav",
      durationInSeconds: 19.674999999999997,
      durationInFrames: 591,
    },
    {
      id: "setup-steps",
      audioFile: "LoggingImplementation/setup-steps.wav",
      durationInSeconds: 24.049999999999997,
      durationInFrames: 722,
    },
    {
      id: "epilogue-code",
      audioFile: "LoggingImplementation/epilogue-code.wav",
      durationInSeconds: 26.975,
      durationInFrames: 810,
    },
    {
      id: "smartdashboard-code",
      audioFile: "LoggingImplementation/smartdashboard-code.wav",
      durationInSeconds: 25.125,
      durationInFrames: 754,
    },
    {
      id: "swerve-pose",
      audioFile: "LoggingImplementation/swerve-pose.wav",
      durationInSeconds: 24.95,
      durationInFrames: 749,
    },
    {
      id: "performance",
      audioFile: "LoggingImplementation/performance.wav",
      durationInSeconds: 21.525,
      durationInFrames: 646,
    },
    {
      id: "viewing",
      audioFile: "LoggingImplementation/viewing.wav",
      durationInSeconds: 20.474999999999998,
      durationInFrames: 615,
    },
    {
      id: "outro",
      audioFile: "LoggingImplementation/outro.wav",
      durationInSeconds: 18.674999999999997,
      durationInFrames: 561,
    },
  ],
  totalDurationInFrames: 5448,
};
