// AUTOGENERATED by `pnpm tts`. Edit Logging.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "Logging",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "Logging/title.wav",
      durationInSeconds: 16.325,
      durationInFrames: 490,
    },
    {
      id: "options",
      audioFile: "Logging/options.wav",
      durationInSeconds: 25.025,
      durationInFrames: 751,
    },
    {
      id: "workshop-choice",
      audioFile: "Logging/workshop-choice.wav",
      durationInSeconds: 21.725,
      durationInFrames: 652,
    },
    {
      id: "advantagescope",
      audioFile: "Logging/advantagescope.wav",
      durationInSeconds: 21.424999999999997,
      durationInFrames: 643,
    },
    {
      id: "outro",
      audioFile: "Logging/outro.wav",
      durationInSeconds: 14.55,
      durationInFrames: 437,
    },
  ],
  totalDurationInFrames: 2973,
};
