// AUTOGENERATED by `pnpm tts`. Edit MechanismSelection.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "MechanismSelection",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "MechanismSelection/title.wav",
      durationInSeconds: 15.725,
      durationInFrames: 472,
    },
    {
      id: "two-options",
      audioFile: "MechanismSelection/two-options.wav",
      durationInSeconds: 19.599999999999998,
      durationInFrames: 588,
    },
    {
      id: "arm-pick",
      audioFile: "MechanismSelection/arm-pick.wav",
      durationInSeconds: 18.7,
      durationInFrames: 561,
    },
    {
      id: "flywheel-pick",
      audioFile: "MechanismSelection/flywheel-pick.wav",
      durationInSeconds: 17.925,
      durationInFrames: 538,
    },
    {
      id: "outro",
      audioFile: "MechanismSelection/outro.wav",
      durationInSeconds: 15.1,
      durationInFrames: 453,
    },
  ],
  totalDurationInFrames: 2612,
};
