// AUTOGENERATED by `pnpm tts`. Edit Prerequisites.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "Prerequisites",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "Prerequisites/title.wav",
      durationInSeconds: 14.225,
      durationInFrames: 427,
    },
    {
      id: "core-software",
      audioFile: "Prerequisites/core-software.wav",
      durationInSeconds: 20.849999999999998,
      durationInFrames: 626,
    },
    {
      id: "tuning-tools",
      audioFile: "Prerequisites/tuning-tools.wav",
      durationInSeconds: 19.125,
      durationInFrames: 574,
    },
    {
      id: "version-control",
      audioFile: "Prerequisites/version-control.wav",
      durationInSeconds: 17.9,
      durationInFrames: 537,
    },
    {
      id: "outro",
      audioFile: "Prerequisites/outro.wav",
      durationInSeconds: 13.25,
      durationInFrames: 398,
    },
  ],
  totalDurationInFrames: 2562,
};
