// AUTOGENERATED by `pnpm tts`. Edit VisionImplementation.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "VisionImplementation",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "VisionImplementation/title.wav",
      durationInSeconds: 17.95,
      durationInFrames: 539,
    },
    {
      id: "strategy",
      audioFile: "VisionImplementation/strategy.wav",
      durationInSeconds: 24.474999999999998,
      durationInFrames: 735,
    },
    {
      id: "limelight-image",
      audioFile: "VisionImplementation/limelight-image.wav",
      durationInSeconds: 18.349999999999998,
      durationInFrames: 551,
    },
    {
      id: "stddev-code",
      audioFile: "VisionImplementation/stddev-code.wav",
      durationInSeconds: 40.925,
      durationInFrames: 1228,
    },
    {
      id: "subsystem-code",
      audioFile: "VisionImplementation/subsystem-code.wav",
      durationInSeconds: 45.9,
      durationInFrames: 1377,
    },
    {
      id: "filtering",
      audioFile: "VisionImplementation/filtering.wav",
      durationInSeconds: 56.175,
      durationInFrames: 1686,
    },
    {
      id: "robotcontainer",
      audioFile: "VisionImplementation/robotcontainer.wav",
      durationInSeconds: 25.025,
      durationInFrames: 751,
    },
    {
      id: "outro",
      audioFile: "VisionImplementation/outro.wav",
      durationInSeconds: 35.375,
      durationInFrames: 1062,
    },
  ],
  totalDurationInFrames: 7929,
};
