// AUTOGENERATED by `pnpm tts`. Edit Vision.script.ts and rerun, not this file.
import type { AudioManifest } from "../lib/types";

export const manifest: AudioManifest = {
  id: "Vision",
  fps: 30,
  segments: [
    {
      id: "title",
      audioFile: "Vision/title.wav",
      durationInSeconds: 17.5,
      durationInFrames: 525,
    },
    {
      id: "options",
      audioFile: "Vision/options.wav",
      durationInSeconds: 20.875,
      durationInFrames: 627,
    },
    {
      id: "limelight",
      audioFile: "Vision/limelight.wav",
      durationInSeconds: 19.15,
      durationInFrames: 575,
    },
    {
      id: "apriltags",
      audioFile: "Vision/apriltags.wav",
      durationInSeconds: 33.15,
      durationInFrames: 995,
    },
    {
      id: "megatag",
      audioFile: "Vision/megatag.wav",
      durationInSeconds: 55.375,
      durationInFrames: 1662,
    },
    {
      id: "filtering",
      audioFile: "Vision/filtering.wav",
      durationInSeconds: 75.65,
      durationInFrames: 2270,
    },
    {
      id: "outro",
      audioFile: "Vision/outro.wav",
      durationInSeconds: 20.75,
      durationInFrames: 623,
    },
  ],
  totalDurationInFrames: 7277,
};
